### ISSUE TITLE
Bungeecord-function: Shutdown Problem at End of the Game

### ISSUE THREAD

**Issue by Tigerpanzer02** [Plajer/Village_Defense#3]
Bungeecord-function: Shutdown Problem at End of the Game
### Sort description of issue
On the End of the Game the Server is not restarting/stopping when all Players manually left the game before the countdown ended... (more Info you have at Discord) 
## Error code
```
No Errors sry ;)
```

## Additional info
- Spigot version:  1.8.8 PaperSpigot
- Plugin version: 3.4.0

(* optional)

**Comment by Plajer** [comment]
Fixed in https://github.com/Plajer/Village_Defense/commit/68881ce9955618a922eac732d2cd3dd98d3636ab 😃
